language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-head
  - jruby-19mode
  - 1.8.7

before_install: |
  sudo apt-get install -qq -y slirp aufs-tools cgroup-lite
  sudo mkdir -p /var/lib/docker
  curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
  chmod +x linux
  curl -sLo docker https://get.docker.io/builds/Linux/x86_64/docker-1.4.1
  chmod +x docker
  chmod +x ./vagrant/travis.sh

install: gem install test-unit mocha

script: |
  rake test
  ./vagrant/travis.sh  

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: 1.8.7
