# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "docker" do |d|
    d.name = 'docker-ssh'
    d.has_ssh = true
    d.build_dir = "."
  end
  config.ssh.username = "root"
  config.ssh.private_key_path = "insecure_phusion.key"
end
